# Generated by Django 2.2.24 on 2022-04-03 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survivors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='survivor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='survivor',
            name='longitude',
        ),
        migrations.AddField(
            model_name='survivor',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='survivors.Location'),
            preserve_default=False,
        ),
    ]
